name: Infracost
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

env:
  TF_ROOT: .
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for retrieving git history

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.0"

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost cost estimate
        uses: infracost/actions/comment@v2
        with:
          path: ${{ env.TF_ROOT }}
          behavior: update
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: table
          show-skipped: false 